<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>b2844cd4-2a8e-4dc4-8b9c-c9f2bc4df50d</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.56.0" />
		<PackageReference Include="Google.Protobuf" Version="3.30.0" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
		<PackageReference Include="Npgsql" Version="9.0.3" />
		<PackageReference Include="Grpc.Tools" Version="2.56.0">
			<PrivateAssets>All</PrivateAssets>
			<IncludeAssets>Runtime;Build;Native;ContentFiles;Analyzers;BuildTransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\Discount.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
