services:
  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings__ConnectionString: "mongodb://catalogdb:27017"
      ASPNETCORE_URLS: "http://+:80"
      DEBUG: "true"
    depends_on:
      catalogdb:
        condition: service_healthy
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/health"]
      interval: 30s
      retries: 3
      start_period: 10s

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379
      - GrpcSettings__DiscountUrl=http://discount.grpc:5004
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - discount.grpc
      - rabbitmq
    ports:
      - "8084:80"

  discount.api:
    container_name: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings__ConnectionString: "Server=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=admin1234"
      ASPNETCORE_URLS: "http://+:80"
      DEBUG: "true"
    depends_on:
      discountdb:
        condition: service_healthy
    ports:
      - "8082:80"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/health"]
      interval: 30s
      retries: 3
      start_period: 10s

  discount.grpc:
    container_name: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings__ConnectionString: "Server=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=admin1234"
      ASPNETCORE_URLS: "http://+:80"
      DEBUG: "true"
    depends_on:
      discountdb:
        condition: service_healthy
    ports:
      - "5044:5004"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/health"]
      interval: 30s
      retries: 3
      start_period: 10s
  
  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P SwN12345678 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 20
      start_period: 180s

  basketdb:
    container_name: basketdb
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - "5672:5672"
        - "15672:15672"
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
 
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ connectionStatus: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  discountdb:
    container_name: discountdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "DiscountDb"]
      interval: 10s
      retries: 5
      start_period: 10s

  ordering.api:
    container_name: ordering.api
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=SA;Password=SwN12345678;TrustServerCertificate=True;Encrypt=False"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    depends_on:
      orderdb:
        condition: service_healthy
    ports:
     - "8090:80"




volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  portainer_data:
